
CYPRESS_VID                 = 0x04B4
PROMETHEUS_PID              = 0x0031
BOOT_PID                    = 0x00BC

CMD_RESET_TO_BOOTMODE       = 0xE0
CMD_START_DEBUG             = 0xB0
CMD_ENTER_FPGA_COMM_MODE    = 0xB1
CMD_ENTER_FPGA_CONFIG_MODE  = 0xB2
CMD_INTERNAL_CONFIG         = 0xB3
CMD_GPIO_CONTROL            = 0xB4

GPIO_FPGA_SOFT_RESET        = 0
GPIO_FPGA_DONE              = 1
GPIO_FPGA_INTERRUPT         = 2
GPIO_FMC_DETECT             = 4
GPIO_FMC_POWER_GOOD_OUT     = 5
GPIO_FMC_POWER_GOOD_IN      = 6


